weights: yolov5s.pt
cfg: yolov5\models\yolov5s.yaml
data: Meta_data\Gird.yaml
hyp: .\yolov5\data\hyp.scratch.yaml
epochs: 100
batch_size: 1
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: Smart-Grid
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs\train\Smart-Grid7
total_batch_size: 1
